version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    ports:
      - '3000:3000'
    command: sh -c 'yarn start:dev'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: postgres:alpine
    container_name: "db-psi"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 3201:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
volumes:
  postgres_data:
